[project]
name = "esphome-pomodoro"
version = "0.2.0"
description = "esphome-pomodoro"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "cairosvg==2.8.2",
    "esphome==2025.6.2",
]
